name: projetocademeutrampo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  image_picker:
  firebase_storage:
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets: 
    - assets/
    - assets/user.png

